# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{wukong}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Philip (flip) Kromer"]
  s.date = %q{2009-10-05}
  s.description = %q{  Treat your dataset like a:

      * stream of lines when it’s efficient to process by lines
      * stream of field arrays when it’s efficient to deal directly with fields
      * stream of lightweight objects when it’s efficient to deal with objects

  Wukong is friends with Hadoop the elephant, Pig the query language, and the cat on your command line.
}
  s.email = %q{flip@infochimps.org}
  s.executables = ["cutc", "cuttab", "greptrue", "hdp-cat", "hdp-catd", "hdp-du", "hdp-get", "hdp-kill", "hdp-ls", "hdp-mkdir", "hdp-mv", "hdp-parts_to_keys.rb", "hdp-ps", "hdp-put", "hdp-rm", "hdp-sort", "hdp-stream", "hdp-stream-flat", "hdp-sync", "hdp-wc", "md5sort", "tabchar", "uniqc", "wu-hist", "wu-lign", "wu-sum"]
  s.extra_rdoc_files = [
    "LICENSE.textile",
     "README.textile"
  ]
  s.files = [
    "doc/INSTALL.textile",
     "doc/LICENSE.textile",
     "doc/README-tutorial.textile",
     "doc/README-wulign.textile",
     "doc/README-wutils.textile",
     "doc/TODO.textile",
     "doc/UsingWukong-part1-setup.textile",
     "doc/UsingWukong-part2-scraping.textile",
     "doc/UsingWukong-part3-parsing.textile",
     "doc/code/api_response_example.txt",
     "doc/code/parser_skeleton.rb",
     "doc/hadoop-nfs.textile",
     "doc/hadoop-setup.textile",
     "doc/index.textile",
     "doc/intro_to_map_reduce/MapReduceDiagram.graffle",
     "doc/links.textile",
     "doc/overview.textile",
     "doc/pig/PigLatinExpressionsList.txt",
     "doc/pig/PigLatinReferenceManual.html",
     "doc/pig/PigLatinReferenceManual.txt",
     "doc/tips.textile",
     "doc/usage.textile",
     "doc/utils.textile",
     "examples/README.txt",
     "examples/and_pig/sample_queries.rb",
     "examples/apache_log_parser.rb",
     "examples/count_keys.rb",
     "examples/count_keys_at_mapper.rb",
     "examples/graph/adjacency_list.rb",
     "examples/graph/breadth_first_search.rb",
     "examples/graph/gen_2paths.rb",
     "examples/graph/gen_multi_edge.rb",
     "examples/graph/gen_symmetric_links.rb",
     "examples/package-local.rb",
     "examples/package.rb",
     "examples/pagerank/README.textile",
     "examples/pagerank/gen_initial_pagerank_graph.pig",
     "examples/pagerank/pagerank.rb",
     "examples/pagerank/pagerank_initialize.rb",
     "examples/pagerank/run_pagerank.sh",
     "examples/rank_and_bin.rb",
     "examples/run_all.sh",
     "examples/sample_records.rb",
     "examples/size.rb",
     "examples/word_count.rb",
     "lib/wukong.rb",
     "lib/wukong/and_pig.rb",
     "lib/wukong/and_pig/README.textile",
     "lib/wukong/and_pig/as.rb",
     "lib/wukong/and_pig/data_types.rb",
     "lib/wukong/and_pig/functions.rb",
     "lib/wukong/and_pig/generate.rb",
     "lib/wukong/and_pig/generate/variable_inflections.rb",
     "lib/wukong/and_pig/junk.rb",
     "lib/wukong/and_pig/operators.rb",
     "lib/wukong/and_pig/operators/compound.rb",
     "lib/wukong/and_pig/operators/evaluators.rb",
     "lib/wukong/and_pig/operators/execution.rb",
     "lib/wukong/and_pig/operators/file_methods.rb",
     "lib/wukong/and_pig/operators/foreach.rb",
     "lib/wukong/and_pig/operators/groupies.rb",
     "lib/wukong/and_pig/operators/load_store.rb",
     "lib/wukong/and_pig/operators/meta.rb",
     "lib/wukong/and_pig/operators/relational.rb",
     "lib/wukong/and_pig/pig_struct.rb",
     "lib/wukong/and_pig/pig_var.rb",
     "lib/wukong/and_pig/symbol.rb",
     "lib/wukong/and_pig/utils.rb",
     "lib/wukong/bad_record.rb",
     "lib/wukong/boot.rb",
     "lib/wukong/datatypes.rb",
     "lib/wukong/datatypes/enum.rb",
     "lib/wukong/dfs.rb",
     "lib/wukong/encoding.rb",
     "lib/wukong/extensions.rb",
     "lib/wukong/extensions/array.rb",
     "lib/wukong/extensions/blank.rb",
     "lib/wukong/extensions/class.rb",
     "lib/wukong/extensions/date_time.rb",
     "lib/wukong/extensions/emittable.rb",
     "lib/wukong/extensions/hash.rb",
     "lib/wukong/extensions/hash_like.rb",
     "lib/wukong/extensions/hashlike_class.rb",
     "lib/wukong/extensions/module.rb",
     "lib/wukong/extensions/pathname.rb",
     "lib/wukong/extensions/string.rb",
     "lib/wukong/extensions/struct.rb",
     "lib/wukong/extensions/symbol.rb",
     "lib/wukong/logger.rb",
     "lib/wukong/models/graph.rb",
     "lib/wukong/rdf.rb",
     "lib/wukong/schema.rb",
     "lib/wukong/script.rb",
     "lib/wukong/script/hadoop_command.rb",
     "lib/wukong/script/local_command.rb",
     "lib/wukong/streamer.rb",
     "lib/wukong/streamer/accumulating_reducer.rb",
     "lib/wukong/streamer/base.rb",
     "lib/wukong/streamer/count_keys.rb",
     "lib/wukong/streamer/count_lines.rb",
     "lib/wukong/streamer/filter.rb",
     "lib/wukong/streamer/line_streamer.rb",
     "lib/wukong/streamer/list_reducer.rb",
     "lib/wukong/streamer/preprocess_with_pipe_streamer.rb",
     "lib/wukong/streamer/rank_and_bin_reducer.rb",
     "lib/wukong/streamer/set_reducer.rb",
     "lib/wukong/streamer/struct_streamer.rb",
     "lib/wukong/streamer/summing_reducer.rb",
     "lib/wukong/streamer/uniq_by_last_reducer.rb",
     "lib/wukong/typed_struct.rb",
     "lib/wukong/wukong_class.rb",
     "spec/bin/hdp-wc_spec.rb",
     "spec/spec_helper.rb",
     "wukong.gemspec"
  ]
  s.homepage = %q{http://github.com/mrflip/wukong}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Wukong makes Hadoop so easy a chimpanzee can use it.}
  s.test_files = [
    "spec/bin/hdp-wc_spec.rb",
     "spec/spec_helper.rb",
     "examples/and_pig/sample_queries.rb",
     "examples/apache_log_parser.rb",
     "examples/count_keys.rb",
     "examples/count_keys_at_mapper.rb",
     "examples/graph/adjacency_list.rb",
     "examples/graph/breadth_first_search.rb",
     "examples/graph/gen_2paths.rb",
     "examples/graph/gen_multi_edge.rb",
     "examples/graph/gen_symmetric_links.rb",
     "examples/package-local.rb",
     "examples/package.rb",
     "examples/pagerank/pagerank.rb",
     "examples/pagerank/pagerank_initialize.rb",
     "examples/rank_and_bin.rb",
     "examples/sample_records.rb",
     "examples/size.rb",
     "examples/word_count.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
