require 'gorillib/model'
require 'gorillib/model/factories'
require 'gorillib/model/serialization'
require 'gorillib/model/serialization/csv'
require 'gorillib/type/extended'

require_relative './airline'
require_relative './airport'
require_relative './route'
require_relative './flight'
