.TH shuffle 1 "12 Apr 1999"
.SH NAME
shuffle \- randomly reorder lines in a file
.SH SYNOPSIS
.B shuffle
[ infile [ outfile ] ]
.SH DESCRIPTION
.B shuffle
reads 
.I infile
into memory, shuffles the lines, and writes
the result to
.IR outfile .
.SH OPTIONS
None.
.SH OPERANDS
The following operands are supported:
.TP 8
.I infile
A path name of an input file.
If no
.I infile
is specified, or if
.I infile
is equal to "\-",
the standard input is used.
.TP 8
.I outfile
A path name of an output file.
If no
.I outfile
is specified, or if
.I outfile
is equal to "\-",
the standard output is used.
.SH NOTES
Since
.B shuffle
reads the input into memory,
it may fail on very large files.
