require 'configliere'
Settings.use :commandline

require_relative '../rake_helper'

Settings.resolve!

Pathname.register_paths(
  project: 'noaa_ish', 
  universe: 'full',

  orig: [Settings.orig_data_root,'orig'],
  scratch: [Settings.scratch_data_root, 'scratch'],
  results: [Settings.results_data_root, 'results'],
  
  #Origin
  noaa_ish_orig: [:orig, 'www1.ncdc.noaa.gov','pub','data','noaa'],
  noaa_ish_test: [:noaa_ish_orig, '010010-99999-2012'],
  #Results
  noaa_ish_results: [:results, :project, :universe],
)

namespace :extract do
  desc 'Extract the NOAA ISH weather data from flat files'
  task :ish do 
    wukong('extract_ish.rb', :noaa_ish_test, :noaa_ish_results)
  end
end
